apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app.snappcloud.io/managed-by: ${SERVICE_NAME}
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: ${SERVICE_NAME}
      name: ${SERVICE_NAME}
    spec:
      host: ${SERVICE_NAME}-${SERVICE_NAMESPACE}.apps.private.teh-1.snappcloud.io
      port:
        targetPort: 9091
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      to:
        kind: Service
        name: ${SERVICE_NAME}

parameters:
  - name: SERVICE_NAME
    displayName: Service name
    required: true
    value: redirtor

  - name: CREATED_BY
    displayName: Service name
    required: true
    value: redirtor

  - name: SERVICE_NAMESPACE
    displayName: Application Unique ID
    required: true
    value: "fintech-development"
