apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.snappcloud.io/name: "${SERVICE_NAME}"
        app.snappcloud.io/managed-by: backend
        app.snappcloud.io/created-by: ${CREATED_BY}
        app: ${SERVICE_NAME}
      name: "${SERVICE_NAME}"
    spec:
      ports:
        - name: "${SERVICE_NAME}-tcp"
          port: 9091
          protocol: TCP
          targetPort: 9091
      selector:
        app: ${SERVICE_NAME}
        deploymentconfig: "${SERVICE_NAME}"
      sessionAffinity: None
      type: ClusterIP

parameters:
  - name: SERVICE_NAME
    displayName: Service name
    required: true
    value: redirector

  - name: CREATED_BY
    displayName: Service name
    required: true
    value: "redirector"

  - name: SERVICE_NAMESPACE
    displayName: Application Unique ID
    required: true
    value: "fintech-development"
